version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build: .
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
